### ISSUE TITLE
The "Save changes" button is inactive after clicking the "Cancel" button on the Profile page

### ISSUE THREAD

**Issue by Oksana-fil** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#102]
The "Save changes" button becomes inactive after clicking on the "Cancel" button on the Profile page.
Note: After the page refreshes "Save change" button becomes active
Note 2: If a user changes their name before clicking on the "Cancel" button it is displayed in the header but in the input fields are displayed one of the previous versions of the name (before saving changes).

Steps to reproduce:
1. Open https://simpleland-development.herokuapp.com/profile
2. Click on the "Cancel" button
3. Enter a valid value into the First name field (Mur)
4. Click on the "Save changes" button
5. Notice that the "Save changes" button is inactive

**Expected result:** The "Save changes" button is active
**Actual result:**  The "Save changes" button is inactive

https://user-images.githubusercontent.com/83494389/227772370-1606a25f-b507-4445-9fa0-a146a6fcf6a7.mp4

**Comment by RemeslovaOksana** [comment]
Looks good, thanks!)
