### ISSUE TITLE
The First name and Last name fields take as valid value with 31 characters

### ISSUE THREAD

**Issue by Oksana-fil** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#104]
The First name and Last name fields take as valid value with 31 characters on the Profile page

Note: related to https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland/issues/80

Pre-condition: The user is registered
Steps to reproduce: 
1. Open https://simpleland-development.herokuapp.com/profile
2. Enter a value into the First name field (Aaaacaaaabaaaacaaaabaaaacaaaaba)
3. Click on the "Save changes" button
4. Notice that the name is saved 

**Actual result:** The First name with a length of 31 characters is saved
**Expected result:** The error message "Incorrect First name" is displayed

**Comment by Oksana-fil** [comment]
![Image](https://user-images.githubusercontent.com/83494389/227772938-9166f362-141b-4809-ab8d-949213cceec6.jpg)

**Comment by jaroslawtt** [comment]
![image](https://user-images.githubusercontent.com/87016333/228128580-e6d7d160-0e2c-4c60-8e45-90d9480ebb5f.png)

**Comment by RemeslovaOksana** [comment]
No error is displayed for Account's name field with 31 characters

![Image](https://user-images.githubusercontent.com/122610949/228320904-c66b6859-574c-4e32-9ff5-9d11bb8d5bb6.png)

**Comment by RemeslovaOksana** [comment]
Tested, looks good!)
