### ISSUE TITLE
Site page

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#114]
We should render the site on frontend on public page `/sites/:id`. For now only 3 sections - harder, footer, main (only with information that we have)

<img width="737" alt="image" src="https://user-images.githubusercontent.com/42296182/228173144-197df808-4970-431f-bc8e-b930cfc2b7da.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/42296182/228173390-40585ab3-02e8-43ca-8999-642dc863e458.png">

**Comment by RemeslovaOksana** [comment]
Looks good, thanks!)
