### ISSUE TITLE
Clickable logo

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#118]
Clicking on the logo will take you to mainpage

**Comment by RemeslovaOksana** [comment]
looks good, but need remove underscore


![Image](https://user-images.githubusercontent.com/122610949/229095226-79b526f5-50d8-469c-b796-8142b2fbb132.png)

**Comment by what1s1ove** [comment]
@kuslosolodka the underscore should be removed

**Comment by RemeslovaOksana** [comment]
@kuslosolodka looks good, thanks!)
