### ISSUE TITLE
The error message contain extra word on the Change password page

### ISSUE THREAD

**Issue by Oksana-fil** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#154]
The error message for the "Repeat New password" contain extra word "be".

Precondition: User should be loggined

Steps to reproduce:
1. Open https://simpleland-development.herokuapp.com/login
2. Click on "Pancil" button for password changing
3. Enter valid value into "New password" inputs
4. Click on the "Save" button 
5. Notice that the error message "Repeat password must be match the password" contain extra word

Expected result: The error message "Repeat New password must match the New password"

**Comment by Oksana-fil** [comment]
![Image](https://user-images.githubusercontent.com/83494389/229291584-f5fad97b-6b7a-4363-974f-d382f2d4e917.jpg)

**Comment by RemeslovaOksana** [comment]
Actual Result: The error message "Repeat password and new password must match"

Expected result: The error message "Repeat New password must match the New password"

**Comment by RemeslovaOksana** [comment]
Looks good, thanks!)
