### ISSUE TITLE
Add a contact block (address, email, phone) to the footer

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#167]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/122610949/229375394-3f767afc-295c-4731-b622-f2bbbceb9ed4.png">

**Comment by what1s1ove** [comment]
address, email and phone should be editable. so you need to add them to the section payload

phone should be only one (without OR)

**Comment by RemeslovaOksana** [comment]
Tested, @kuslosolodka thanks!)
