### ISSUE TITLE
Add a social media block (Twitter, LinkedIn, Facebook) to the footer

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#168]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/122610949/229375528-1ec232b2-362d-422b-bbec-4ec450edd7da.png">

**Comment by what1s1ove** [comment]
just link with a `#`

**Comment by RemeslovaOksana** [comment]
Looks good!)
@Alyona-Pisotska thanks!)
