### ISSUE TITLE
All tabs are underlined in Account setting page

### ISSUE THREAD

**Issue by Oksana-fil** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#195]
All tabs are displayed underlined on the Account setting page

Precondition: User is logged

Steps to reproduce:
1. Open https://simpleland-development.herokuapp.com/profile
2. Notice that all tabs are underlined

Expected result: Only chosen tab is underlined

**Comment by Oksana-fil** [comment]
![Image](https://user-images.githubusercontent.com/83494389/229888892-27575e18-1cc1-403d-a771-8baa678e843e.jpg)

**Comment by RemeslovaOksana** [comment]
Tested, looks good!)
@Alexandr-mas thanks!)
