### ISSUE TITLE
The new Email field is fulfilled with the email in use on the Change email pop-up

### ISSUE THREAD

**Issue by Oksana-fil** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#197]
1. The new Email field is fulfilled with the email in use on the Change email pop-up on the Account setting page
2. The text in the Repeat email field is incorrect "Enter your first name"

Precondition: User is logged

Steps to reproduce:
1. Open https://simpleland-development.herokuapp.com/login
2. Click on the "Pencil" button in the email field
3. Notice that the Email field is filled 

1. Expected result: The field for new email is empty (or contains placeholder text "Enter your new email")
2. Expected result: The text in the Repeat email field is "Repeat your new email"

**Comment by Oksana-fil** [comment]
![Image](https://user-images.githubusercontent.com/83494389/229900144-a0c98008-d002-436a-834b-8e11228232c9.jpg)

**Comment by Alyona-Pisotska** [comment]
we have this task
[Email update - one field#161](https://github.com/BinaryStudioAcademy/bsa-winter-2022-2023-simpleland/issues/161)

**Comment by Oksana-fil** [comment]
Duplicate
