### ISSUE TITLE
Steps validation message

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#224]
**Description:**
Move сheck steps message

**Steps to reproduce:**
1. Open created project
2. Click "Add site" button

**Actual Result:**
<img width="358" alt="image" src="https://user-images.githubusercontent.com/122610949/230591921-da778584-c87c-4333-812b-ee0c30f7cd91.png">

**Expected Result:**
<img width="383" alt="image" src="https://user-images.githubusercontent.com/122610949/230592076-68ed57bf-9ed8-46e3-aa4b-e9115b222018.png">

**Severity:**
Trivial (S4)

**Comment by Alyona-Pisotska** [comment]
I fixed in sl-171: Final step design task

**Comment by RemeslovaOksana** [comment]
Implemented in sl-171: Final step design task
