### ISSUE TITLE
The name of the error on the first step (site name)

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#226]
**Description:**
Change the name of the error on the first step

**Steps to reproduce:**
1. Open project 
2. Click on the "add site" button 
3. Click on the "Go next" button 

**Actual Result:**
The error message "Project name is required"

**Expected Result:**
The error message "Site name is required"

**Visual Proof (screenshots, videos, text):**
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/122610949/230602533-d6ef5b2d-e751-4cf0-92b0-e1411d06c9c8.png">

**Severity:**
Trivial (S4)

**Comment by Oksana-fil** [comment]
Tested and verified. Looks nice, thanks!
