### ISSUE TITLE
Change name "Landing" to "My sites"

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#242]
Change name "Landing" to "My sites"
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/122610949/230723833-ca4b9439-dd67-4bba-a036-a6851649974b.png">

**Comment by what1s1ove** [comment]
it should be a name of current project

**Comment by RemeslovaOksana** [comment]
Tested, looks good!)
@jaroslawtt thanks!)
