### ISSUE TITLE
Add a navigation block to the header 

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#251]
they shouldn't be editable

<img width="312" alt="image" src="https://user-images.githubusercontent.com/42296182/230848002-e756dac7-1071-4d69-8e86-42fab81839bd.png">

these 4 types
![image](https://user-images.githubusercontent.com/42296182/230848080-b04a945c-78ca-478c-95f3-6e7e28f87df6.png)

**Comment by RemeslovaOksana** [comment]
Tested, looks good!
@Alyona-Pisotska thanks!)
