### ISSUE TITLE
Domains page

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#253]
All buttons should be disabled with tooltips that we will add this functionality soon. Probably add "lock" icons and etc

<img width="765" alt="image" src="https://user-images.githubusercontent.com/42296182/230848520-cbdaebda-bf8f-46ce-aa63-8b675bf49d68.png">

**Comment by RemeslovaOksana** [comment]
Looks good!)
@Alyona-Pisotska thanks!)
