### ISSUE TITLE
Move edit button (my projects page)

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#272]
The button should be above the project image
<img width="340" alt="image" src="https://user-images.githubusercontent.com/122610949/231089717-f75d7100-b88b-41b5-9ccb-7157db416f9f.png">

**Comment by what1s1ove** [comment]
should be visible only by the user hover on the project

**Comment by RemeslovaOksana** [comment]
Looks good!)
@Alyona-Pisotska thanks!)
