### ISSUE TITLE
Edit sections functionality (underline input)

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#274]
Inputs that can be change by the user should be underlined.
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/122610949/231101586-720acf2f-03d1-4031-a211-3d912697db55.png">

**Comment by what1s1ove** [comment]
actually it should be for all sections

**Comment by what1s1ove** [comment]
@RemeslovaOksana could you take a look?

**Comment by RemeslovaOksana** [comment]
Add underline input in service section

**Comment by RemeslovaOksana** [comment]
Tested, looks good!)
@jaroslawtt thanks!)
