### ISSUE TITLE
Fix text entry form (in all section)

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#286]
**Description:**
Fix text entry form (in all section)

**Actual Result:**
The text input form can be stretched in all directions

**Expected Result:**
The text input form can only stretch down

**Visual Proof (screenshots, videos, text):**

https://user-images.githubusercontent.com/122610949/231254098-cec804a1-f2d3-4db1-9a24-b10314392ac1.mov

**Severity:**
Trivial (S4)

**Comment by what1s1ove** [comment]
remove resize from textarea

**Comment by RemeslovaOksana** [comment]
Looks good, thanks!)
