### ISSUE TITLE
Indents not showing after editing

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#322]
**Description:**
indents not showing after editing (all sections)

**Visual Proof (screenshots, videos, text):**

https://user-images.githubusercontent.com/122610949/231576491-dadf1e25-8788-479d-a751-b6639a0e42f8.mov

**Severity:**
Major (S2)

**Comment by what1s1ove** [comment]
Expected for now
