### ISSUE TITLE
Editing the titles

### ISSUE THREAD

**Issue by RemeslovaOksana** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#323]
**Description:**
Editing the title Service section (also the name of each block), title portfolio section, title feedback section (also the name and surname and position)

**Actual Result:**
When editing, part of the title disappears

**Expected Result:**
When editing, the entire title is displayed

**Visual Proof (screenshots, videos, text):**

https://user-images.githubusercontent.com/122610949/231577785-c5c5d4e3-4e34-4c46-86f7-9992558fd19c.mov

**Severity:**
Major (S2)

**Comment by what1s1ove** [comment]
expected for now
