### ISSUE TITLE
User popover

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#57]
by clicking on the user avatar we need to open the popup with user many
items for now
- profile (`/profile`)
- logout (mock for now)
<img width="295" alt="image" src="https://user-images.githubusercontent.com/42296182/226850150-cdbea39a-e3e4-44da-951d-8c02e92453b7.png">

**Comment by Oksana-fil** [comment]
Tested and verified. Looks nice, thanks!
