### ISSUE TITLE
User logout functionality

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#58]
By clicking on the "logout" in the user must log out of their platform

**Comment by jaroslawtt** [comment]
All I should do is to create action that would clear user data from state and remove token from cookies? Or there is something essential else?

**Comment by what1s1ove** [comment]
Yes, in this action you need to clear all user data @jaroslawtt

**Comment by Oksana-fil** [comment]
Tested and verified. It's work! Thanks!
