### ISSUE TITLE
/start page

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#62]
Implement `/start` page according to the design. Add `Stepper` with 0 items for now

<img width="646" alt="image" src="https://user-images.githubusercontent.com/42296182/227178646-40edc1b5-cc13-48df-adab-a4b9b6ed1d14.png">

**Comment by Oksana-fil** [comment]
Tested and verified. Looks nice, thanks!
