### ISSUE TITLE
/my-projects empty placeholder 

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#65]
Add this placeholder on the `/my-projects` page where there are no any projects

<img width="878" alt="image" src="https://user-images.githubusercontent.com/42296182/227243643-e17af3a2-90e1-462e-91a3-2b3facd9e77d.png">

**Comment by RemeslovaOksana** [comment]
Does not match the design. Other background color



![Image](https://user-images.githubusercontent.com/122610949/228279495-37368c6d-426d-4b72-b199-1047d42bb367.png)

**Comment by RemeslovaOksana** [comment]
Good job!)
