### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#7]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/42296182/224629309-977142ee-5055-448c-8e2e-c1e245b214a1.png">

- [x] create user_details table
- [x] Migration -> Controller
- [x] Validation

**Comment by RemeslovaOksana** [comment]
Tested, looks good.
Thanks
