### ISSUE TITLE
Add logo to Header/Auth page & open graph and favico to website

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#89]
OG should be like this - https://metatags.io/
<img width="699" alt="image" src="https://user-images.githubusercontent.com/42296182/227763322-29f98746-45dc-45f7-91ff-3adf696fe243.png">

**Comment by jaroslawtt** [comment]
Can I get description and title for open graph somewhere?

**Comment by what1s1ove** [comment]
@jaroslawtt ask our QAs

**Comment by RemeslovaOksana** [comment]
Looks good!
