### ISSUE TITLE
Create business fuctionality

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#91]
By clicking on "Add a business " we need to render a modal with a business modal. By submitting with form, the new business should be create.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/42296182/227763720-a08a106e-2b51-4cc4-9b72-b8bf317cbf88.png">

**Comment by RemeslovaOksana** [comment]
Tested, looks good!
