### ISSUE TITLE
Change password functionality

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#98]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/42296182/227765721-acee5b3a-a540-44c1-bb27-b1c15596d9b6.png">

**Comment by what1s1ove** [comment]
work in pair with @jaroslawtt

**Comment by Oksana-fil** [comment]
Nice work, thanks!
