### ISSUE TITLE
Change login functionality

### ISSUE THREAD

**Issue by what1s1ove** [BinaryStudioAcademy/bsa-winter-2022-2023-simpleland#99]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/42296182/227765730-dd383077-aaaa-42d0-b3aa-77b0207206a2.png">

**Comment by jaroslawtt** [comment]
Not clearly understand what user can do with field password from accout setting login section (not from modal for changing password). Should user provide his password in this field in case user want to change login or what?

**Comment by RemeslovaOksana** [comment]
Tested, looks good! Thanks!)
